consul:
  host: http://196.168.1.43:8500
  datacenter: beijing
  service:
    name: msg-center
    tags:
    - msg-center
    - http
    port: 8080
    id: msg-center-1
  services:
    - AppServer
  keys:
    - datacenter/sqldb
    - datacenter/redis
ip: 196.168.1.43:8080
env: development
log:
  debug: true
  log_dir: "./logs"
  log_max_size: 10
  log_max_backups: 3
  log_max_age: 7
  log_compress: false

