consul:
  host: http://196.168.1.43:8500
  datacenter: beijing
  service:
    name: msg-center
    tags:
    - msg-center
    - http
    port: 8080
    id: msg-center-1
  services:
    - AppServer
  keys:
    - datacenter/sqldb
    - datacenter/redis
ip: 196.168.1.43:8080